/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class AggregationInfo {
  private transient long cPointer;
  protected transient boolean owner;

  protected AggregationInfo(long cPtr, boolean cMemoryOwn) {
    owner = cMemoryOwn;
    cPointer = cPtr;
  }

  protected static long getCPtr(AggregationInfo obj) {
    return (obj == null) ? 0 : obj.cPointer;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (cPointer != 0) {
      if (owner) {
        owner = false;
        JNI.delete_AggregationInfo(cPointer);
      }
      cPointer = 0;
    }
  }

  public static AggregationInfo FromMsgHash(PublicKey pk, byte[] messageHash) {
    return new AggregationInfo(JNI.AggregationInfo_FromMsgHash(PublicKey.getCPtr(pk), pk, messageHash), true);
  }

  public static AggregationInfo FromMsg(PublicKey pk, byte[] message, long len) {
    return new AggregationInfo(JNI.AggregationInfo_FromMsg(PublicKey.getCPtr(pk), pk, message, len), true);
  }

  public static AggregationInfo FromVectors(PublicKeyVector pubKeys, MessageHashVector messageHashes, BigIntegerVector exponents) {
    return new AggregationInfo(JNI.AggregationInfo_FromVectors(PublicKeyVector.getCPtr(pubKeys), pubKeys, MessageHashVector.getCPtr(messageHashes), messageHashes, BigIntegerVector.getCPtr(exponents), exponents), true);
  }

  public static AggregationInfo MergeInfos(AggregationInfoVector infos) {
    return new AggregationInfo(JNI.AggregationInfo_MergeInfos(AggregationInfoVector.getCPtr(infos)), true);
  }

  public AggregationInfo(AggregationInfo info) {
    this(JNI.new_AggregationInfo__SWIG_0(AggregationInfo.getCPtr(info), info), true);
  }

  public void RemoveEntries(MessageHashVector messages, PublicKeyVector pubKeys) {
    JNI.AggregationInfo_RemoveEntries(cPointer, this, MessageHashVector.getCPtr(messages), messages, PublicKeyVector.getCPtr(pubKeys), pubKeys);
  }

  public void GetExponent(SWIGTYPE_p_bn_t result, byte[] messageHash, PublicKey pubkey) {
    JNI.AggregationInfo_GetExponent(cPointer, this, SWIGTYPE_p_bn_t.getCPtr(result), messageHash, PublicKey.getCPtr(pubkey), pubkey);
  }

  public PublicKeyVector GetPubKeys() {
    return new PublicKeyVector(JNI.AggregationInfo_GetPubKeys(cPointer, this), true);
  }

  public MessageHashVector GetMessageHashes() {
    return new MessageHashVector(JNI.AggregationInfo_GetMessageHashes(cPointer, this), true);
  }

  public boolean Empty() {
    return JNI.AggregationInfo_Empty(cPointer, this);
  }

  public AggregationInfo() {
    this(JNI.new_AggregationInfo__SWIG_1(), true);
  }

}
