/*
 * Copyright 2018 Dash Core Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was generated by SWIG (http://www.swig.org) and modified.
 * Version 3.0.12
 */

package org.dashj.bls;

public class AggregationInfo {
  private transient long cPointer;
  protected transient boolean owner;

  protected AggregationInfo(long cPtr, boolean cMemoryOwn) {
    owner = cMemoryOwn;
    cPointer = cPtr;
  }

  protected static long getCPtr(AggregationInfo obj) {
    return (obj == null) ? 0 : obj.cPointer;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (cPointer != 0) {
      if (owner) {
        owner = false;
        JNI.delete_AggregationInfo(cPointer);
      }
      cPointer = 0;
    }
  }

  public static AggregationInfo FromMsgHash(PublicKey pk, byte[] messageHash) {
    return new AggregationInfo(JNI.AggregationInfo_FromMsgHash(PublicKey.getCPtr(pk), pk, messageHash), true);
  }

  public static AggregationInfo FromMsg(PublicKey pk, byte[] message, long len) {
    return new AggregationInfo(JNI.AggregationInfo_FromMsg(PublicKey.getCPtr(pk), pk, message, len), true);
  }

  public static AggregationInfo FromVectors(PublicKeyVector pubKeys, MessageHashVector messageHashes, BigIntegerVector exponents) {
    return new AggregationInfo(JNI.AggregationInfo_FromVectors(PublicKeyVector.getCPtr(pubKeys), pubKeys, MessageHashVector.getCPtr(messageHashes), messageHashes, BigIntegerVector.getCPtr(exponents), exponents), true);
  }

  public static AggregationInfo MergeInfos(AggregationInfoVector infos) {
    return new AggregationInfo(JNI.AggregationInfo_MergeInfos(AggregationInfoVector.getCPtr(infos)), true);
  }

  public AggregationInfo(AggregationInfo info) {
    this(JNI.new_AggregationInfo__SWIG_0(AggregationInfo.getCPtr(info), info), true);
  }

  public void RemoveEntries(MessageHashVector messages, PublicKeyVector pubKeys) {
    JNI.AggregationInfo_RemoveEntries(cPointer, this, MessageHashVector.getCPtr(messages), messages, PublicKeyVector.getCPtr(pubKeys), pubKeys);
  }

  public void GetExponent(SWIGTYPE_p_bn_t result, byte[] messageHash, PublicKey pubkey) {
    JNI.AggregationInfo_GetExponent(cPointer, this, SWIGTYPE_p_bn_t.getCPtr(result), messageHash, PublicKey.getCPtr(pubkey), pubkey);
  }

  public PublicKeyVector GetPubKeys() {
    return new PublicKeyVector(JNI.AggregationInfo_GetPubKeys(cPointer, this), true);
  }

  public MessageHashVector GetMessageHashes() {
    return new MessageHashVector(JNI.AggregationInfo_GetMessageHashes(cPointer, this), true);
  }

  public boolean Empty() {
    return JNI.AggregationInfo_Empty(cPointer, this);
  }

  public AggregationInfo() {
    this(JNI.new_AggregationInfo__SWIG_1(), true);
  }

}
