/*
 * Copyright 2018 Dash Core Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was generated by SWIG (http://www.swig.org) and modified.
 * Version 3.0.12
 */

package org.dashj.bls;

public class BigIntegerVector extends java.util.AbstractList<SWIGTYPE_p_bn_t> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BigIntegerVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BigIntegerVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNI.delete_BigIntegerVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  BigIntegerVector(java.util.Collection<SWIGTYPE_p_bn_t> e) {
    this.reserve(e.size());
    for(SWIGTYPE_p_bn_t value: e) {
      this.push_back(value);
    }
  }

  public BigIntegerVector() {
    this(JNI.new_BigIntegerVec__SWIG_0(), true);
  }

  public BigIntegerVector(long n) {
    this(JNI.new_BigIntegerVec__SWIG_1(n), true);
  }

  public BigIntegerVector(BigIntegerVector o) {
    this(JNI.new_BigIntegerVec__SWIG_2(BigIntegerVector.getCPtr(o), o), true);
  }

  public long capacity() {
    return JNI.BigIntegerVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    JNI.BigIntegerVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return JNI.BigIntegerVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    JNI.BigIntegerVec_clear(swigCPtr, this);
  }

  public void push_back(SWIGTYPE_p_bn_t x) {
    JNI.BigIntegerVec_push_back(swigCPtr, this, SWIGTYPE_p_bn_t.getCPtr(x));
  }

  public SWIGTYPE_p_bn_t get(int i) {
    long cPtr = JNI.BigIntegerVec_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bn_t(cPtr, false);
  }

  public SWIGTYPE_p_bn_t set(int i, SWIGTYPE_p_bn_t VECTOR_VALUE_IN) {
    long cPtr = JNI.BigIntegerVec_set(swigCPtr, this, i, SWIGTYPE_p_bn_t.getCPtr(VECTOR_VALUE_IN));
    return (cPtr == 0) ? null : new SWIGTYPE_p_bn_t(cPtr, false);
  }

  public int size() {
    return JNI.BigIntegerVec_size(swigCPtr, this);
  }

  public void removeRange(int from, int to) {
    JNI.BigIntegerVec_removeRange(swigCPtr, this, from, to);
  }

}
