/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.bls;

public class PrivateKey extends BLSObject {

  protected PrivateKey(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(PrivateKey obj) {
    return (obj == null) ? 0 : obj.cPointer;
  }

  public synchronized void delete() {
        JNI.delete_PrivateKey(cPointer);
  }

  public static PrivateKey FromSeed(byte[] seed, long seedLen) {
    return new PrivateKey(JNI.PrivateKey_FromSeed(seed, seedLen), true);
  }

  public static PrivateKey FromBytes(byte[] bytes, boolean modOrder) {
    return new PrivateKey(JNI.PrivateKey_FromBytes__SWIG_0(bytes, modOrder), true);
  }

  public static PrivateKey FromBytes(byte[] bytes) {
    return new PrivateKey(JNI.PrivateKey_FromBytes__SWIG_1(bytes), true);
  }

  public PrivateKey(PrivateKey k) {
    this(JNI.new_PrivateKey__SWIG_0(PrivateKey.getCPtr(k), k), true);
  }

  public PublicKey GetPublicKey() {
    return new PublicKey(JNI.PrivateKey_GetPublicKey(cPointer, this), true);
  }

  public static PrivateKey AggregateInsecure(PrivateKeyVector privateKeys) {
    return new PrivateKey(JNI.PrivateKey_AggregateInsecure(PrivateKeyVector.getCPtr(privateKeys), privateKeys), true);
  }

  public static PrivateKey Aggregate(PrivateKeyVector privateKeys, PublicKeyVector pubKeys) {
    return new PrivateKey(JNI.PrivateKey_Aggregate(PrivateKeyVector.getCPtr(privateKeys), privateKeys, PublicKeyVector.getCPtr(pubKeys)), true);
  }

  public void Serialize(byte[] buffer) {
    JNI.PrivateKey_Serialize__SWIG_0(cPointer, this, buffer);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_char_t Serialize() {
    return new SWIGTYPE_p_std__vectorT_unsigned_char_t(JNI.PrivateKey_Serialize__SWIG_1(cPointer, this), true);
  }

  public InsecureSignature SignInsecure(byte[] msg, long len) {
    return new InsecureSignature(JNI.PrivateKey_SignInsecure(cPointer, this, msg, len), true);
  }

  public InsecureSignature SignInsecurePrehashed(byte[] hash) {
    return new InsecureSignature(JNI.PrivateKey_SignInsecurePrehashed(cPointer, this, hash), true);
  }

  public Signature Sign(byte[] msg, long len) {
    return new Signature(JNI.PrivateKey_Sign(cPointer, this, msg, len), true);
  }

  public Signature SignPrehashed(byte[] hash) {
    return new Signature(JNI.PrivateKey_SignPrehashed(cPointer, this, hash), true);
  }

  public final static long PRIVATE_KEY_SIZE = JNI.PrivateKey_PRIVATE_KEY_SIZE_get();
}
