// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storedserverpaymentchannel.proto

package org.bitcoinj.protocols.channels;

public final class ServerState {
  private ServerState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface StoredServerPaymentChannelsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:paymentchannels.StoredServerPaymentChannels)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    java.util.List<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> 
        getChannelsList();
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel getChannels(int index);
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    int getChannelsCount();
  }
  /**
   * <pre>
   * A set of StoredPaymentChannel's
   * </pre>
   *
   * Protobuf type {@code paymentchannels.StoredServerPaymentChannels}
   */
  public  static final class StoredServerPaymentChannels extends
      com.google.protobuf.GeneratedMessageLite<
          StoredServerPaymentChannels, StoredServerPaymentChannels.Builder> implements
      // @@protoc_insertion_point(message_implements:paymentchannels.StoredServerPaymentChannels)
      StoredServerPaymentChannelsOrBuilder {
    private StoredServerPaymentChannels() {
      channels_ = emptyProtobufList();
    }
    public static final int CHANNELS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> channels_;
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> getChannelsList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    public java.util.List<? extends org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannelOrBuilder> 
        getChannelsOrBuilderList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    @java.lang.Override
    public int getChannelsCount() {
      return channels_.size();
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    @java.lang.Override
    public org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel getChannels(int index) {
      return channels_.get(index);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    public org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannelOrBuilder getChannelsOrBuilder(
        int index) {
      return channels_.get(index);
    }
    private void ensureChannelsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> tmp = channels_;
      if (!tmp.isModifiable()) {
        channels_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void setChannels(
        int index, org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
      value.getClass();
  ensureChannelsIsMutable();
      channels_.set(index, value);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addChannels(org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
      value.getClass();
  ensureChannelsIsMutable();
      channels_.add(value);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addChannels(
        int index, org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
      value.getClass();
  ensureChannelsIsMutable();
      channels_.add(index, value);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addAllChannels(
        java.lang.Iterable<? extends org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> values) {
      ensureChannelsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, channels_);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void clearChannels() {
      channels_ = emptyProtobufList();
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void removeChannels(int index) {
      ensureChannelsIsMutable();
      channels_.remove(index);
    }

    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * A set of StoredPaymentChannel's
     * </pre>
     *
     * Protobuf type {@code paymentchannels.StoredServerPaymentChannels}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels, Builder> implements
        // @@protoc_insertion_point(builder_implements:paymentchannels.StoredServerPaymentChannels)
        org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannelsOrBuilder {
      // Construct using org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      @java.lang.Override
      public java.util.List<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> getChannelsList() {
        return java.util.Collections.unmodifiableList(
            instance.getChannelsList());
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      @java.lang.Override
      public int getChannelsCount() {
        return instance.getChannelsCount();
      }/**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      @java.lang.Override
      public org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel getChannels(int index) {
        return instance.getChannels(index);
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
        copyOnWrite();
        instance.setChannels(index, value);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
        copyOnWrite();
        instance.setChannels(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
        copyOnWrite();
        instance.addChannels(value);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
        copyOnWrite();
        instance.addChannels(index, value);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
        copyOnWrite();
        instance.addChannels(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
        copyOnWrite();
        instance.addChannels(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addAllChannels(
          java.lang.Iterable<? extends org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> values) {
        copyOnWrite();
        instance.addAllChannels(values);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder clearChannels() {
        copyOnWrite();
        instance.clearChannels();
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder removeChannels(int index) {
        copyOnWrite();
        instance.removeChannels(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredServerPaymentChannels)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "channels_",
              org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel.class,
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0001\u0001\u041b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels> parser = PARSER;
          if (parser == null) {
            synchronized (org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:paymentchannels.StoredServerPaymentChannels)
    private static final org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels DEFAULT_INSTANCE;
    static {
      StoredServerPaymentChannels defaultInstance = new StoredServerPaymentChannels();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        StoredServerPaymentChannels.class, defaultInstance);
    }

    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannels getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StoredServerPaymentChannels> PARSER;

    public static com.google.protobuf.Parser<StoredServerPaymentChannels> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface StoredServerPaymentChannelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:paymentchannels.StoredServerPaymentChannel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     * @return Whether the bestValueToMe field is set.
     */
    boolean hasBestValueToMe();
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     * @return The bestValueToMe.
     */
    long getBestValueToMe();

    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     * @return Whether the bestValueSignature field is set.
     */
    boolean hasBestValueSignature();
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     * @return The bestValueSignature.
     */
    com.google.protobuf.ByteString getBestValueSignature();

    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     * @return Whether the refundTransactionUnlockTimeSecs field is set.
     */
    boolean hasRefundTransactionUnlockTimeSecs();
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     * @return The refundTransactionUnlockTimeSecs.
     */
    long getRefundTransactionUnlockTimeSecs();

    /**
     * <code>required bytes contractTransaction = 4;</code>
     * @return Whether the contractTransaction field is set.
     */
    boolean hasContractTransaction();
    /**
     * <code>required bytes contractTransaction = 4;</code>
     * @return The contractTransaction.
     */
    com.google.protobuf.ByteString getContractTransaction();

    /**
     * <code>optional bytes clientOutput = 5;</code>
     * @return Whether the clientOutput field is set.
     */
    boolean hasClientOutput();
    /**
     * <code>optional bytes clientOutput = 5;</code>
     * @return The clientOutput.
     */
    com.google.protobuf.ByteString getClientOutput();

    /**
     * <code>required bytes myKey = 6;</code>
     * @return Whether the myKey field is set.
     */
    boolean hasMyKey();
    /**
     * <code>required bytes myKey = 6;</code>
     * @return The myKey.
     */
    com.google.protobuf.ByteString getMyKey();

    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     * @return Whether the majorVersion field is set.
     */
    boolean hasMajorVersion();
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     * @return The majorVersion.
     */
    int getMajorVersion();

    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     * @return Whether the clientKey field is set.
     */
    boolean hasClientKey();
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     * @return The clientKey.
     */
    com.google.protobuf.ByteString getClientKey();
  }
  /**
   * <pre>
   * A server-side payment channel in serialized form, which can be reloaded later if the server restarts
   * </pre>
   *
   * Protobuf type {@code paymentchannels.StoredServerPaymentChannel}
   */
  public  static final class StoredServerPaymentChannel extends
      com.google.protobuf.GeneratedMessageLite<
          StoredServerPaymentChannel, StoredServerPaymentChannel.Builder> implements
      // @@protoc_insertion_point(message_implements:paymentchannels.StoredServerPaymentChannel)
      StoredServerPaymentChannelOrBuilder {
    private StoredServerPaymentChannel() {
      bestValueSignature_ = com.google.protobuf.ByteString.EMPTY;
      contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
      clientOutput_ = com.google.protobuf.ByteString.EMPTY;
      myKey_ = com.google.protobuf.ByteString.EMPTY;
      majorVersion_ = 1;
      clientKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int BESTVALUETOME_FIELD_NUMBER = 1;
    private long bestValueToMe_;
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     * @return Whether the bestValueToMe field is set.
     */
    @java.lang.Override
    public boolean hasBestValueToMe() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     * @return The bestValueToMe.
     */
    @java.lang.Override
    public long getBestValueToMe() {
      return bestValueToMe_;
    }
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     * @param value The bestValueToMe to set.
     */
    private void setBestValueToMe(long value) {
      bitField0_ |= 0x00000001;
      bestValueToMe_ = value;
    }
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     */
    private void clearBestValueToMe() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bestValueToMe_ = 0L;
    }

    public static final int BESTVALUESIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bestValueSignature_;
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     * @return Whether the bestValueSignature field is set.
     */
    @java.lang.Override
    public boolean hasBestValueSignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     * @return The bestValueSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBestValueSignature() {
      return bestValueSignature_;
    }
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     * @param value The bestValueSignature to set.
     */
    private void setBestValueSignature(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      bestValueSignature_ = value;
    }
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     */
    private void clearBestValueSignature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bestValueSignature_ = getDefaultInstance().getBestValueSignature();
    }

    public static final int REFUNDTRANSACTIONUNLOCKTIMESECS_FIELD_NUMBER = 3;
    private long refundTransactionUnlockTimeSecs_;
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     * @return Whether the refundTransactionUnlockTimeSecs field is set.
     */
    @java.lang.Override
    public boolean hasRefundTransactionUnlockTimeSecs() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     * @return The refundTransactionUnlockTimeSecs.
     */
    @java.lang.Override
    public long getRefundTransactionUnlockTimeSecs() {
      return refundTransactionUnlockTimeSecs_;
    }
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     * @param value The refundTransactionUnlockTimeSecs to set.
     */
    private void setRefundTransactionUnlockTimeSecs(long value) {
      bitField0_ |= 0x00000004;
      refundTransactionUnlockTimeSecs_ = value;
    }
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     */
    private void clearRefundTransactionUnlockTimeSecs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      refundTransactionUnlockTimeSecs_ = 0L;
    }

    public static final int CONTRACTTRANSACTION_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString contractTransaction_;
    /**
     * <code>required bytes contractTransaction = 4;</code>
     * @return Whether the contractTransaction field is set.
     */
    @java.lang.Override
    public boolean hasContractTransaction() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bytes contractTransaction = 4;</code>
     * @return The contractTransaction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContractTransaction() {
      return contractTransaction_;
    }
    /**
     * <code>required bytes contractTransaction = 4;</code>
     * @param value The contractTransaction to set.
     */
    private void setContractTransaction(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
      contractTransaction_ = value;
    }
    /**
     * <code>required bytes contractTransaction = 4;</code>
     */
    private void clearContractTransaction() {
      bitField0_ = (bitField0_ & ~0x00000008);
      contractTransaction_ = getDefaultInstance().getContractTransaction();
    }

    public static final int CLIENTOUTPUT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString clientOutput_;
    /**
     * <code>optional bytes clientOutput = 5;</code>
     * @return Whether the clientOutput field is set.
     */
    @java.lang.Override
    public boolean hasClientOutput() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes clientOutput = 5;</code>
     * @return The clientOutput.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientOutput() {
      return clientOutput_;
    }
    /**
     * <code>optional bytes clientOutput = 5;</code>
     * @param value The clientOutput to set.
     */
    private void setClientOutput(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000010;
      clientOutput_ = value;
    }
    /**
     * <code>optional bytes clientOutput = 5;</code>
     */
    private void clearClientOutput() {
      bitField0_ = (bitField0_ & ~0x00000010);
      clientOutput_ = getDefaultInstance().getClientOutput();
    }

    public static final int MYKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString myKey_;
    /**
     * <code>required bytes myKey = 6;</code>
     * @return Whether the myKey field is set.
     */
    @java.lang.Override
    public boolean hasMyKey() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required bytes myKey = 6;</code>
     * @return The myKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMyKey() {
      return myKey_;
    }
    /**
     * <code>required bytes myKey = 6;</code>
     * @param value The myKey to set.
     */
    private void setMyKey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000020;
      myKey_ = value;
    }
    /**
     * <code>required bytes myKey = 6;</code>
     */
    private void clearMyKey() {
      bitField0_ = (bitField0_ & ~0x00000020);
      myKey_ = getDefaultInstance().getMyKey();
    }

    public static final int MAJORVERSION_FIELD_NUMBER = 7;
    private int majorVersion_;
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     * @return Whether the majorVersion field is set.
     */
    @java.lang.Override
    public boolean hasMajorVersion() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     * @return The majorVersion.
     */
    @java.lang.Override
    public int getMajorVersion() {
      return majorVersion_;
    }
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     * @param value The majorVersion to set.
     */
    private void setMajorVersion(int value) {
      bitField0_ |= 0x00000040;
      majorVersion_ = value;
    }
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     */
    private void clearMajorVersion() {
      bitField0_ = (bitField0_ & ~0x00000040);
      majorVersion_ = 1;
    }

    public static final int CLIENTKEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString clientKey_;
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     * @return Whether the clientKey field is set.
     */
    @java.lang.Override
    public boolean hasClientKey() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     * @return The clientKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientKey() {
      return clientKey_;
    }
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     * @param value The clientKey to set.
     */
    private void setClientKey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000080;
      clientKey_ = value;
    }
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     */
    private void clearClientKey() {
      bitField0_ = (bitField0_ & ~0x00000080);
      clientKey_ = getDefaultInstance().getClientKey();
    }

    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * A server-side payment channel in serialized form, which can be reloaded later if the server restarts
     * </pre>
     *
     * Protobuf type {@code paymentchannels.StoredServerPaymentChannel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel, Builder> implements
        // @@protoc_insertion_point(builder_implements:paymentchannels.StoredServerPaymentChannel)
        org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannelOrBuilder {
      // Construct using org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       * @return Whether the bestValueToMe field is set.
       */
      @java.lang.Override
      public boolean hasBestValueToMe() {
        return instance.hasBestValueToMe();
      }
      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       * @return The bestValueToMe.
       */
      @java.lang.Override
      public long getBestValueToMe() {
        return instance.getBestValueToMe();
      }
      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       * @param value The bestValueToMe to set.
       * @return This builder for chaining.
       */
      public Builder setBestValueToMe(long value) {
        copyOnWrite();
        instance.setBestValueToMe(value);
        return this;
      }
      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBestValueToMe() {
        copyOnWrite();
        instance.clearBestValueToMe();
        return this;
      }

      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       * @return Whether the bestValueSignature field is set.
       */
      @java.lang.Override
      public boolean hasBestValueSignature() {
        return instance.hasBestValueSignature();
      }
      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       * @return The bestValueSignature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBestValueSignature() {
        return instance.getBestValueSignature();
      }
      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       * @param value The bestValueSignature to set.
       * @return This builder for chaining.
       */
      public Builder setBestValueSignature(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBestValueSignature(value);
        return this;
      }
      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBestValueSignature() {
        copyOnWrite();
        instance.clearBestValueSignature();
        return this;
      }

      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       * @return Whether the refundTransactionUnlockTimeSecs field is set.
       */
      @java.lang.Override
      public boolean hasRefundTransactionUnlockTimeSecs() {
        return instance.hasRefundTransactionUnlockTimeSecs();
      }
      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       * @return The refundTransactionUnlockTimeSecs.
       */
      @java.lang.Override
      public long getRefundTransactionUnlockTimeSecs() {
        return instance.getRefundTransactionUnlockTimeSecs();
      }
      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       * @param value The refundTransactionUnlockTimeSecs to set.
       * @return This builder for chaining.
       */
      public Builder setRefundTransactionUnlockTimeSecs(long value) {
        copyOnWrite();
        instance.setRefundTransactionUnlockTimeSecs(value);
        return this;
      }
      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRefundTransactionUnlockTimeSecs() {
        copyOnWrite();
        instance.clearRefundTransactionUnlockTimeSecs();
        return this;
      }

      /**
       * <code>required bytes contractTransaction = 4;</code>
       * @return Whether the contractTransaction field is set.
       */
      @java.lang.Override
      public boolean hasContractTransaction() {
        return instance.hasContractTransaction();
      }
      /**
       * <code>required bytes contractTransaction = 4;</code>
       * @return The contractTransaction.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContractTransaction() {
        return instance.getContractTransaction();
      }
      /**
       * <code>required bytes contractTransaction = 4;</code>
       * @param value The contractTransaction to set.
       * @return This builder for chaining.
       */
      public Builder setContractTransaction(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContractTransaction(value);
        return this;
      }
      /**
       * <code>required bytes contractTransaction = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractTransaction() {
        copyOnWrite();
        instance.clearContractTransaction();
        return this;
      }

      /**
       * <code>optional bytes clientOutput = 5;</code>
       * @return Whether the clientOutput field is set.
       */
      @java.lang.Override
      public boolean hasClientOutput() {
        return instance.hasClientOutput();
      }
      /**
       * <code>optional bytes clientOutput = 5;</code>
       * @return The clientOutput.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClientOutput() {
        return instance.getClientOutput();
      }
      /**
       * <code>optional bytes clientOutput = 5;</code>
       * @param value The clientOutput to set.
       * @return This builder for chaining.
       */
      public Builder setClientOutput(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientOutput(value);
        return this;
      }
      /**
       * <code>optional bytes clientOutput = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientOutput() {
        copyOnWrite();
        instance.clearClientOutput();
        return this;
      }

      /**
       * <code>required bytes myKey = 6;</code>
       * @return Whether the myKey field is set.
       */
      @java.lang.Override
      public boolean hasMyKey() {
        return instance.hasMyKey();
      }
      /**
       * <code>required bytes myKey = 6;</code>
       * @return The myKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMyKey() {
        return instance.getMyKey();
      }
      /**
       * <code>required bytes myKey = 6;</code>
       * @param value The myKey to set.
       * @return This builder for chaining.
       */
      public Builder setMyKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMyKey(value);
        return this;
      }
      /**
       * <code>required bytes myKey = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMyKey() {
        copyOnWrite();
        instance.clearMyKey();
        return this;
      }

      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       * @return Whether the majorVersion field is set.
       */
      @java.lang.Override
      public boolean hasMajorVersion() {
        return instance.hasMajorVersion();
      }
      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       * @return The majorVersion.
       */
      @java.lang.Override
      public int getMajorVersion() {
        return instance.getMajorVersion();
      }
      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       * @param value The majorVersion to set.
       * @return This builder for chaining.
       */
      public Builder setMajorVersion(int value) {
        copyOnWrite();
        instance.setMajorVersion(value);
        return this;
      }
      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       * @return This builder for chaining.
       */
      public Builder clearMajorVersion() {
        copyOnWrite();
        instance.clearMajorVersion();
        return this;
      }

      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       * @return Whether the clientKey field is set.
       */
      @java.lang.Override
      public boolean hasClientKey() {
        return instance.hasClientKey();
      }
      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       * @return The clientKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClientKey() {
        return instance.getClientKey();
      }
      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       * @param value The clientKey to set.
       * @return This builder for chaining.
       */
      public Builder setClientKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientKey(value);
        return this;
      }
      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientKey() {
        copyOnWrite();
        instance.clearClientKey();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredServerPaymentChannel)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "bestValueToMe_",
              "bestValueSignature_",
              "refundTransactionUnlockTimeSecs_",
              "contractTransaction_",
              "clientOutput_",
              "myKey_",
              "majorVersion_",
              "clientKey_",
            };
            java.lang.String info =
                "\u0001\b\u0000\u0001\u0001\b\b\u0000\u0000\u0004\u0001\u1503\u0000\u0002\u100a\u0001" +
                "\u0003\u1503\u0002\u0004\u150a\u0003\u0005\u100a\u0004\u0006\u150a\u0005\u0007\u100b" +
                "\u0006\b\u100a\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel> parser = PARSER;
          if (parser == null) {
            synchronized (org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:paymentchannels.StoredServerPaymentChannel)
    private static final org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel DEFAULT_INSTANCE;
    static {
      StoredServerPaymentChannel defaultInstance = new StoredServerPaymentChannel();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        StoredServerPaymentChannel.class, defaultInstance);
    }

    public static org.bitcoinj.protocols.channels.ServerState.StoredServerPaymentChannel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StoredServerPaymentChannel> PARSER;

    public static com.google.protobuf.Parser<StoredServerPaymentChannel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
